### ISSUE TITLE
UTF-8 Fail Fast

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-testsuite#1]
Actually, we should distinguish the following behaviors:

fail-per-message
fail-per-frame
fail-per-buffered
fail-per-first-octet (aka fail-fast)

"""
probably this is something which would be  good reason to make that case section "informational" .. because the probably most sensible beh. (fail-per-buffered) is not canonical/well-defined anyway. mmh

it could be tested: start with N*valid char + invalid .. gradually increase N from 0 to 128k .. that should cover up most fail-per-buffered

actually: 6.4.3 should be extended so that it does that increasing N test. it would then report N*, the first N at which the peer detected invalid utf8.

for fail-fast: N\* would be 0
for fail-per-buffer: N\* would be the impl. buffer size

and it would fail if N\* > N .. that is the impl. only does per-frame/per-msg val.
"""

**Comment by vinniefalco** [comment]
I have an issue with this test as well. It depends on the test sending a close message in response to the server, in the middle of the payload.

**Comment by jchampio** [comment]
> You can see the last 6 payload bytes getting sent after the close (Line 11 in Wire Log)

I think Line 11 shows the octets of the transmitted Close frame, doesn't it?

> Passing the test means that the other end has to send a close message in the middle of a frame payload? And the server has to assume that the last 6 bytes of the expected frame payload are not going to be received?

I don't think that's what has to happen to pass the test -- mod_websocket passes the test without making that assumption, so I think the only success criteria is that the server sends a fail-fast Close frame.

I do agree with you that the fuzzingclient seems to be destroying its own frame boundary, at least if I'm reading the log right. Whether or not that's incredibly important for the purposes of this automated test, I don't know, since part of the point of the fuzzingclient is to break the protocol and see what the server does. Is your implementation failing the test?

(I'm not affiliated with Autobahn, by the way -- just a fellow client.)

**Comment by vinniefalco** [comment]
@jchampio Thanks for responding. My original implementation upon sending a close during fail-fast utf8 was to read and discard the remaining bytes in the current frame payload, then go into a loop reading and discarding frames until getting a close frame. This implementation failed the autobahn tests. On a lark I tried going straight to expecting the close frame and it passed the test. Then I did a little digging and figure out that autobahn is breaking a frame boundary.

I agree that the purpose of the test is to break the protocol, but I don't think its correct behavior to say that when a client breaks the protocol, the server is expected to act a certain way. It should be possible for an implementation to assume that frames sent by the remote will not be sent in the middle of the payload of the current frame, without failing the autobahn tests. It seems that passing the test relies on a certain behavior of TCP/IP which is not guaranteed.

In case anyone is wondering, this is what I did in my code:
https://github.com/vinniefalco/rippled/blob/server/src/beast/beast/wsproto/impl/read_op.ipp#L206
I wanted to go into state "6" which finishes out the payload and discards frames but this does not pass the tests. Going straight into "7", which expects a new frame, passes the test.

**Comment by jchampio** [comment]
> I don't think its correct behavior to say that when a client breaks the protocol, the server is expected to act a certain way.

I disagree; in most cases RFC 6455 lays out clear requirements for endpoint behavior when a peer violates the protocol. See below.

> My original implementation upon sending a close during fail-fast utf8 was to read and discard the remaining bytes in the current frame payload, then go into a loop reading and discarding frames until getting a close frame. This implementation failed the autobahn tests.

That's because this behavior violates the spec. From [8.1](https://tools.ietf.org/html/rfc6455#section-8.1):

    When an endpoint is to interpret a byte stream as UTF-8 but finds
    that the byte stream is not, in fact, a valid UTF-8 stream, that
    endpoint MUST _Fail the WebSocket Connection_.

And from the definition of `Fail the WebSocket Connection` in [7.1.7](https://tools.ietf.org/html/rfc6455#section-7.1.7):

    [...] An endpoint MUST NOT continue to attempt to
    process data (including a responding Close frame) from the remote
    endpoint after being instructed to _Fail the WebSocket Connection_.

So IMO it's fairly clear: a server should send an explanatory `1007` close code, then close the connection without continuing to read anything.

**Comment by vinniefalco** [comment]
@jchampio That's exactly the clarity that I was looking for, thanks!

**Comment by oberstet** [comment]
rgd my original issue / scope of this issue: wont fix. i dont think it's worth, and more so, so many implementations out there are tested and rely on the current behavior and test scope of this testsuite that I'd expect a lot of discussions;)
