### ISSUE TITLE
Any plans to support Python 3?

### ISSUE THREAD

**Issue by raimundmuc** [crossbario/autobahn-testsuite#104]
Python 2 is dead since about a month ago ... are there any plans to support Python 3 one day?

**Comment by oberstet** [comment]
no plans, as we don't have the resources. some more notes:

* we recommend using the Docker image https://github.com/crossbario/autobahn-testsuite#using-the-testsuite-docker-image
* the testsuite pins Autobahn at an old version https://github.com/crossbario/autobahn-testsuite/blob/72620ad515a039e1e17198c1018211471371dfcf/autobahntestsuite/setup.py#L88
* https://github.com/crossbario/autobahn-testsuite/pull/83 has started some work on this
* lifting the testsuite to the latest Autobahn would make it support Py3 - but work, plus comes with risks (the behavior of the testsuite should stay constant .. so that it is usable to develop websocket libs/servers)
