### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by ioquatix** [crossbario/autobahn-testsuite#126]
Any chance of a plan or statement regarding python 3 support?

Even using the docker image, I see warnings, e.g.

```
> docker run -it --rm -v "$(pwd)/config:/config" -v "$(pwd)/reports:/reports" --name wstest crossbario/autobahn-testsuite
Unable to find image 'crossbario/autobahn-testsuite:latest' locally
latest: Pulling from crossbario/autobahn-testsuite
e22122b926a1: Pull complete 
f29e09ae8373: Pull complete 
e319e3daef68: Pull complete 
e499244fe254: Pull complete 
5a6ebed20e89: Pull complete 
8c433b46ce14: Pull complete 
bcc9ab79cfa7: Pull complete 
9e080db9f095: Pull complete 
6f8b10b35f43: Pull complete 
510a500f9039: Pull complete 
Digest: sha256:5d4ba3aa7d6ab2fdbf6606f3f4ecbe4b66f205ce1cbc176d6cdf650157e52242
Status: Downloaded newer image for crossbario/autobahn-testsuite:latest
/opt/pypy/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
...
```

**Comment by oberstet** [comment]
fwiw, I've recently added some notes here https://github.com/crossbario/autobahn-testsuite/issues/45#issuecomment-1413319820

**Comment by jhoughjr** [comment]
I'm wondering if these still work?
I attempted to test a chrome websocket client against the docker image and nothing seems to happen.
I see Entering direct command mode for peer tcp4:172.17.0.1:55784 when it opens, but no reports, no cpu usage or disk access. 

When my client sent about 6k of PMCE deflate data, it seemed to throw an exception.
So I made my client just connect and sit, expecting the server to do something.

The docs don't seem clear on what to expect for a successful test or what the clients are to do.
I expected some kind of passing or failing reports from Chrome after 20 minutes but there is no further output.
I'm on m1 if that is relevant running an amd64 docker image.

**Comment by mcallegari** [comment]
I add myself to this, since I recently integrated a Qt websocket library in my project.
Autobahn is referenced from the official Qt documentation:
https://doc.qt.io/qt-6/qtwebsockets-testing.html

However, I spent two hours trying to make it work on Linux without any luck. Among [broken links](https://github.com/crossbario/autobahn-python/blob/master/examples/twisted/websocket/testee), wrong information and Python failures, there's no way to make Autobahn work on modern Linux distribution (I tried on Ubuntu 22.04)

Can you please consider the task to port Autobahn to Python3 with a higher priority?
Or at least write an up-to-date documentation to have wstest working on Python3.

Thank you!

**Comment by oberstet** [comment]
AutobahnPython works from PyPI via pip on any Python 3 (Python 2 isn't supported anymore on later releases). More so, the former is true not only for CPython but also PyPy.

AutobahnTestsuite is using internally an old snapshot of AutobahnPython - a version which still did had support for Python 2.

AutobahnTestsuite is doing a lot of crazy things internally ("fuzzing"). It has grown suprisingly complex I can tell you. Keeping the exact behavior of this crazyness *exactly constant* is

**feature number 1!**

Making the internal crazyness run on Python 3 rather than Python 2 does not add any benefit.

It introduces a big risk, I'd practically a certainty that we fail on the above feature 1 while doing the latter.

In the case, the end result would be: huge mess, confused users of AutobahnTestsuite, endless streams of "regressions" or what, broken CIs, ...

I do no think that would be welcome for anyone.

For users. And certainly not for me. I simply to not have time for such pointless (my view) exercises.

Do you @mcallegari ?

**Comment by oberstet** [comment]
https://github.com/crossbario/autobahn-testsuite?tab=readme-ov-file#using-the-testsuite-docker-image

**Comment by oberstet** [comment]
as a user of AutobahnTestsuite, you can (and should) completely forget about anything Python.

doesn't matter.

run the Docker image above which works both for testee = websocket server and for client

done.

**Comment by ioquatix** [comment]
If anyone is interested in a working example of a github workflow: https://github.com/socketry/protocol-websocket/blob/main/.github/workflows/autobahn-server-tests.yaml

**Comment by ioquatix** [comment]
I think the main concern is that as Python 2 is EOL and eventually even this docker image may stop working.

**Comment by oberstet** [comment]
> and eventually even this docker image may stop working

why?

*access to the binary bits starting from gcc right up into AutobahnPython will be possible to be reproduced exactly - forever (GOAL) is sth be ideally would like to aim at. and the current status - in principle - not far away .. I'd say.*

this is of course the crux of the matter anyways

**repeatability of tests** and **stability of tests tools** is *essential*

if one is missing, of what value are (any) tests then anyways?

I mean, "value" for the app developer, with the app code under development being the main/only thing of interest (to the app developer)

**Comment by ioquatix** [comment]
In my experience, assuming things like docker will work the same way forever is probably unrealistic.

My main concern was this warning:

> /opt/pypy/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509

While the image may work, eventually a new version of TLS may be released, or something else may change, and that will be practically impossible to support, etc. If Python 3 support is not planned, feel free to close this issue.

**Comment by oberstet** [comment]
> While the image may work, eventually a new version of TLS may be released, or something else may change

sure! but that does not change 1 bit in the image that I do have. and the bits for that image reside on my local disk. and copies reside on N disks around the globe. and ensuring we are talking about the exact same bits of said image is easy. SHA256. done.

did I miss anything?

**Comment by oberstet** [comment]
taking your example, when we update the AutobahnTestsuite image to use a newer base OS, a newer TLS library (OpenSSL) therein, a new Python run-time - and thus not change anything at the Python level, the question that matters then (rgd whether AutobahnTestsuite continues to work) is:

Do the **pinned** versions of Python and Python TLS and Python XYZ and AutobahnTestsuite vN.M all still work with the updated OS base?

This of course is not always true.

If it is true, then everything (the exact pinned versions) could be said to be "forward compatible" with respect to the new base OS versions.

**Comment by ioquatix** [comment]
All that's totally fine..

I'm glad you are maintaining this in a sustainable way that suits you. I'm grateful for this test suite and I'll continue to use it as is for as long as possible.

However I can imagine over time, Python 2 will become a hindrance to outside contributions. For example, I did run into issues trying to make this work without docker, and I feel like that is a barrier to entry for contributing to this project. However, that may not be an issue - again totally fine.

If I had any suggestion it would simply be to clarify this, e.g. in addition to this:

> Right now we only support Python 2 and Python 3 will not work

Simply state that Python 3 support is not planned.

**Comment by oberstet** [comment]
> Simply state that Python 3 support is not planned.

even more precise: we only _support_ our own official Docker images, and "support" done by "we" as in me and some guys around is on a "as we like / maybe" basis

> become a hindrance to outside contributions

the biggest hindrance in my impression to outside contributions to AutobahnTestsuite is not anything related to what you hint at, but simply having the know-how (about RFC6455) and the code base (which is pretty tricky)

porting to python 3 does not help at all with that, but would add yet one more dimension to the puzzle

**Comment by ioquatix** [comment]
I implemented a full implementation of WebSockets for Ruby, including both HTTP/1 and HTTP/2 support. So I'm not unqualified.

> the biggest hindrance in my impression to outside contributions to AutobahnTestsuite is not anything related to what you hint at,

This is absolutely a problem for me, but it's okay if that's not a priority for you. I simply gave up trying to set up an appropriate development environment.

**Comment by oberstet** [comment]
Just to leave no wrong impression:

* if you would want to contribute to AutobahnTestsuite itself, that would be highly welcome!!
* if so, then I didn't got that right, as I thought you want to _use_ the testsuite
* if you want to contribute, let me know, I could help of course, my help in this thread until now was under the assumption of you aiming for "user role".
* however, "developer role", of course, cool! be ready for hardcore though. this stuff is not for the faint hearted. not saying about you, but just so that you have no unrealistic expectations.
